# Generated by Django 3.2.5 on 2021-07-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movies.Genre', verbose_name='Жанры'),
        ),
    ]
